### PR TITLE
Move the modules to their respective plugin

### PR DESCRIPTION
**Pull request by cmoulliard**
- Move the modules to their respective plugin
- Issue: #103

### CODE REVIEW

**Review by aureamunoz — COMMENTED** [review]
Could we rename `backstage-playground/plugins` to `backstage-playground/modules`?

**Comment by cmoulliard** [comment]
> Could we rename `backstage-playground/plugins` to `backstage-playground/modules`?

Yes. Great proposition :-)

**Review by aureamunoz — APPROVED** [review]
LGTM

**Review by iocanel — APPROVED** [review]
LGMT

**Pull request merged**
