### PR TITLE
dev now passes local config

### PR DESCRIPTION
**Pull request by iocanel**

### CODE REVIEW

**Review by cmoulliard — CHANGES_REQUESTED** [review]
Can you mention within the README.md file that a user can start locally the front + backend using the `app-config.qshift.local.yaml` file ?

**Review by cmoulliard — APPROVED** [review]

**Comment by cmoulliard** [comment]
We should review what we will do with this PR as it is already possible to launch using `yarn dev` the front + backend but in this case using `app-config.yaml` and `app-config.local.yaml`

**Comment by cmoulliard** [comment]
This PR should be closed - Yes/No @iocanel

**Comment by iocanel** [comment]
Yeah, this has been already implemented by other PRs.

**Pull request closed without merging**
